### ISSUE TITLE
Remove Dropdown list from collection tile

### ISSUE THREAD

**Issue by mannprerak2** [put-away/putaway#13]
The dropdown list only contains 1 item - Edit Name.
The dropdown list should be removed and instead an Edit button should be added.

**Comment by tronicdata** [comment]
I want to try to work on this.

**Comment by tronicdata** [comment]
Where can I find the dropdown list this is referring to? @mannprerak2

**Comment by mannprerak2** [comment]
Here you go: https://github.com/mannprerak2/putaway/blob/27ee27b010391d6d486ee839ff11ef45040a5169/src/components/tiles/CollectionTile.svelte#L270

**Comment by tronicdata** [comment]
@mannprerak2 Thanks, I see it now
