### ISSUE TITLE
Replace Utf8 icons with Font awesome Icons

### ISSUE THREAD

**Issue by mannprerak2** [put-away/putaway#5]
Icons to replace:
- Search
- Bin
- Save

**Comment by asubedy** [comment]
I would like to work on it. Please assign me.

**Comment by asubedy** [comment]
Is it cool if I install this Font Awesome 5 Svelte component and import it in the code?
https://www.npmjs.com/package/sveltejs-fontawesome

**Comment by mannprerak2** [comment]
Yes, just make sure to import only what you need so that svelte compiler can perform treeshaking

**Comment by mannprerak2** [comment]
Closed via #11 and #9
